# Generated by Django 4.2.26 on 2026-01-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
