# Generated by Django 5.2.9 on 2026-01-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocker', models.EmailField(db_index=True, max_length=254)),
                ('blocked', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
