# Generated by Django 5.2.9 on 2026-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_message_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('auth_provider', models.CharField(default='email', max_length=50)),
                ('django_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('google_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('onboarding_step', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('drinking', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking', models.CharField(blank=True, max_length=50, null=True)),
                ('workout', models.CharField(blank=True, max_length=50, null=True)),
                ('pets', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship_goals', models.JSONField(blank=True, default=list)),
                ('sexual_orientation', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('communication_style', models.JSONField(blank=True, default=list)),
                ('response_pace', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('conversation_starter', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
