# Generated by Django 5.2.9 on 2026-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_userauth_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relationship_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
