# Generated by Django 5.2.9 on 2026-02-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_userprofile_relationship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
