# Generated by Django 5.2.9 on 2026-02-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_userphoto_user_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(db_index=True, max_length=254)),
                ('type', models.CharField(choices=[('MATCH_CREATED', 'Match Created'), ('NEW_MESSAGE', 'New Message'), ('LIKE_RECEIVED', 'Like Received')], max_length=50)),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
