# Generated by Django 5.2.9 on 2026-02-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
