# Generated by Django 5.2.9 on 2026-02-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('show_online', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'privacy_preferences',
            },
        ),
    ]
