# Generated by Django 5.2.9 on 2026-02-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_privacypreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='age_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userauth',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userauth',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
