# Generated by Django 5.2.9 on 2026-01-27 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('eye', 'Eye'), ('zap', 'Zap'), ('message-circle', 'Message Circle'), ('map-pin', 'Map Pin'), ('shield', 'Shield'), ('star', 'Star'), ('heart', 'Heart'), ('crown', 'Crown')], default='star', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Feature',
                'verbose_name_plural': 'Premium Features',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('plan_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', '6 Months'), ('annual', 'Annual')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_text', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(choices=[('zap', 'Zap'), ('flame', 'Flame'), ('trending-up', 'Trending Up'), ('crown', 'Crown')], default='zap', max_length=20)),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', max_length=100)),
                ('gradient', models.CharField(default='bg-gradient-to-br from-blue-500 to-cyan-500', max_length=100)),
                ('popular', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list, help_text='List of features for this plan')),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Plan',
                'verbose_name_plural': 'Premium Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
    ]
