# Generated by Django 5.2.9 on 2026-01-27 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_userreport_options_userreport_chat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='message_snapshot',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='reported_message',
        ),
        migrations.AlterField(
            model_name='userreport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('fake', 'Fake Profile'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='userreport',
            table='user_reports',
        ),
    ]
