# Generated by Django 5.2.9 on 2026-01-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_premiumfeature_premiumplan'),
        ('admin_panel', '0003_alter_userreport_options_remove_userreport_chat_and_more'),
    ]

    operations = [
    ]
