# Generated by Django 5.2.9 on 2026-01-29 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_merge_20260129_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Expert's name", max_length=100)),
                ('role', models.CharField(help_text="Expert's role/title", max_length=100)),
                ('image', models.URLField(help_text="URL to expert's profile image (e.g., https://i.pravatar.cc/150?img=11)", max_length=500)),
                ('tip', models.TextField(help_text='The expert tip text')),
                ('icon', models.CharField(choices=[('message-circle', 'Message Circle'), ('target', 'Target'), ('sparkles', 'Sparkles'), ('lightbulb', 'Lightbulb'), ('heart', 'Heart'), ('star', 'Star'), ('zap', 'Zap'), ('users', 'Users'), ('trending-up', 'Trending Up')], default='lightbulb', max_length=20)),
                ('icon_color', models.CharField(choices=[('text-blue-500', 'Blue'), ('text-rose-500', 'Rose'), ('text-amber-500', 'Amber'), ('text-violet-500', 'Violet'), ('text-green-500', 'Green'), ('text-purple-500', 'Purple'), ('text-pink-500', 'Pink'), ('text-teal-500', 'Teal')], default='text-blue-500', max_length=20)),
                ('bg_color', models.CharField(choices=[('bg-blue-50', 'Blue'), ('bg-rose-50', 'Rose'), ('bg-amber-50', 'Amber'), ('bg-violet-50', 'Violet'), ('bg-green-50', 'Green'), ('bg-purple-50', 'Purple'), ('bg-pink-50', 'Pink'), ('bg-teal-50', 'Teal')], default='bg-blue-50', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Whether this tip is displayed')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which tips appear (lower = first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expert Tip',
                'verbose_name_plural': 'Expert Tips',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
