# Generated by Django 5.2.9 on 2026-01-31 06:39

import admin_panel.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='experttip',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experttip',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experttip',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experttip',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experttip',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experttip',
            name='tip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=admin_panel.models._default_permissions)),
                ('invite_token', models.CharField(blank=True, default=admin_panel.models._generate_invite_token, max_length=64, null=True, unique=True)),
                ('invite_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'db_table': 'admin_roles',
                'ordering': ['-created_at'],
            },
        ),
    ]
