# Generated by Django 5.2.9 on 2026-02-01 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_experttip_active_alter_experttip_display_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the admin was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='initial_password',
            field=models.CharField(blank=True, help_text='Temporary password generated on account creation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='password_changed',
            field=models.BooleanField(default=False, help_text='True if admin has changed their password from the initial one'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='adminrole',
            index=models.Index(fields=['is_active'], name='admin_roles_is_acti_e1f55d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminrole',
            index=models.Index(fields=['deleted_at'], name='admin_roles_deleted_15a20b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminrole',
            index=models.Index(fields=['user', 'is_active'], name='admin_roles_user_id_43b231_idx'),
        ),
    ]
