# Generated by Django 5.2.9 on 2026-02-02 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_footersection_footersettings_footerlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promo code (e.g., SUMMER2024, FREEMONTH100)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description (not shown to users)')),
                ('discount_percentage', models.IntegerField(default=100, help_text='Discount percentage (100 = FREE)')),
                ('max_uses', models.IntegerField(default=100, help_text='Maximum number of people who can use this code')),
                ('current_uses', models.IntegerField(default=0, help_text='Current number of times used')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this code becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this code expires (leave empty for no expiration)', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this code is currently active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='Which plan this code applies to', on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='admin_panel.premiumplan')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.premiumplan')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='admin_panel.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'db_table': 'promo_code_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promo_codes_code_5b1d05_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['active'], name='promo_codes_active_e504b4_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['user'], name='promo_code__user_id_b12e12_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['promo_code'], name='promo_code__promo_c_469618_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('promo_code', 'user')},
        ),
    ]
