# Generated by Django 5.2.9 on 2026-02-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_merge_20260129_1807'),
        ('admin_panel', '0010_promocode_promocodeusage_and_more'),
    ]

    operations = [
    ]
