# Generated by Django 5.2.9 on 2026-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_merge_20260205_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumplan',
            name='icon',
            field=models.CharField(choices=[('zap', 'Zap'), ('flame', 'Flame'), ('trending-up', 'Trending Up'), ('crown', 'Crown'), ('star', 'Star')], default='zap', max_length=20),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
