# Generated by Django 5.2.9 on 2026-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_premiumsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
