# Generated by Django 5.2.9 on 2026-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_userreport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='daily_swipe_limit',
            field=models.IntegerField(blank=True, help_text='Max swipes per day for this plan. NULL = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='monthly_connection_limit',
            field=models.IntegerField(blank=True, help_text='Max likes/connections per month. NULL = unlimited.', null=True),
        ),
    ]
