# Generated by Django 4.2.26 on 2025-12-28 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('show_gender', models.BooleanField(default=True)),
                ('interested_in', models.JSONField(blank=True, default=list)),
                ('orientation', models.JSONField(blank=True, default=list)),
                ('show_orientation', models.BooleanField(default=True)),
                ('relationship_type', models.CharField(blank=True, max_length=100)),
                ('distance', models.IntegerField(default=25)),
                ('strict_distance', models.BooleanField(default=False)),
                ('drinking', models.CharField(blank=True, max_length=50)),
                ('smoking', models.CharField(blank=True, max_length=50)),
                ('workout', models.CharField(blank=True, max_length=50)),
                ('pets', models.CharField(blank=True, max_length=50)),
                ('communication_style', models.JSONField(blank=True, default=list)),
                ('response_pace', models.CharField(blank=True, max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('use_current_location', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('conversation_starter', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
