# Generated by Django 4.2.26 on 2025-12-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_accounts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
