# Generated by Django 4.2.26 on 2026-01-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_social_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='relationship_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_orientation',
        ),
    ]
