# Generated by Django 5.2.9 on 2026-02-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_account_status_userprofile_active_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relationship_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
