# Generated by Django 5.2.9 on 2026-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_relationship_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo_count',
            new_name='onboarding_step',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='photos',
            new_name='relationship_goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='conversation_starter',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexual_orientation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='relationship_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
