# Generated by Django 5.2.9 on 2026-02-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_photo_count_userprofile_onboarding_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
