# Generated by Django 5.2.9 on 2026-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='swipes_used',
            field=models.IntegerField(default=0),
        ),
    ]
