# Generated by Django 5.2.9 on 2026-03-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userprofile_swipes_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='swipes_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
